# Generated by Django 2.1.7 on 2019-04-05 19:24

from django.db import migrations, models
import django.db.models.deletion
import opinion.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crewing', '0025_auto_20190401_1423'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата отзыва')),
                ('author', models.CharField(db_index=True, max_length=64, verbose_name='Автор отзыва')),
                ('opinion_text', models.TextField(verbose_name='Отзыв')),
                ('opinion_file', models.FileField(blank=True, default=None, null=True, upload_to=opinion.models.get_opinionfile_path, verbose_name='Файл')),
                ('contract', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewing.Contracts', verbose_name='Контракт')),
                ('seaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewing.Seamans', verbose_name='Моряк')),
            ],
            options={
                'verbose_name': 'Отзыв',
                'verbose_name_plural': 'отзывы',
                'ordering': ['-date'],
            },
        ),
    ]
