# Generated by Django 2.1.7 on 2019-04-05 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crewing', '0026_auto_20190405_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ability360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.CharField(db_index=True, max_length=32, verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Компетенция',
                'verbose_name_plural': 'Компетенции',
            },
        ),
        migrations.CreateModel(
            name='Question360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(db_index=True, max_length=128, verbose_name='Вопрос')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Ability360', verbose_name='Компетенция')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['ability', 'question'],
            },
        ),
        migrations.CreateModel(
            name='RankAbilityQuestion360',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Ability360')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Question360')),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewing.Ranks')),
            ],
        ),
        migrations.CreateModel(
            name='Scoring360AbilitySum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ability_value', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Оценка')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Ability360', verbose_name='Компетенция')),
                ('seaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewing.Seamans', verbose_name='Моряк')),
            ],
            options={
                'verbose_name': 'Суммарная оценка по компетенции',
            },
        ),
        migrations.CreateModel(
            name='Scoring360SeamanAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Метка времени')),
                ('ability', models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Компетенция')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise_from', to='crewing.Seamans', verbose_name='Кто оценивал')),
                ('seaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise_to', to='crewing.Seamans', verbose_name='Оцениваемый моряк')),
            ],
            options={
                'verbose_name': 'Оценка 360',
                'verbose_name_plural': 'Оценки 360',
                'ordering': ['seaman', 'date'],
            },
        ),
        migrations.AddField(
            model_name='question360',
            name='rank',
            field=models.ManyToManyField(related_name='question', through='scoring_360.RankAbilityQuestion360', to='crewing.Ranks', verbose_name='Должность'),
        ),
    ]
