# Generated by Django 2.1.7 on 2019-04-05 21:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scoring360seamanability',
            name='ability_value',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Оценка'),
        ),
        migrations.AlterField(
            model_name='scoring360seamanability',
            name='ability',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Ability360', verbose_name='Компетенция'),
            preserve_default=False,
        ),
    ]
