# Generated by Django 2.1.7 on 2019-04-08 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0028_auto_20190408_1246'),
        ('scoring_360', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ability360',
            name='ranks',
            field=models.ManyToManyField(related_name='abilities', to='crewing.Ranks', verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='question360',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='scoring_360.Ability360', verbose_name='Компетенция'),
        ),
    ]
