# Generated by Django 2.1.7 on 2019-04-08 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_360', '0003_auto_20190408_1312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scoring360abilitysum',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='scoring360abilitysum',
            name='seaman',
        ),
        migrations.RemoveField(
            model_name='scoring360seamanability',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='scoring360seamanability',
            name='appraiser',
        ),
        migrations.RemoveField(
            model_name='scoring360seamanability',
            name='seaman',
        ),
        migrations.DeleteModel(
            name='Scoring360AbilitySum',
        ),
        migrations.DeleteModel(
            name='Scoring360SeamanAbility',
        ),
    ]
