# Generated by Django 2.1.7 on 2019-04-08 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0031_auto_20190408_1553'),
        ('scoring_360', '0005_auto_20190408_1555'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rankabilityquestion',
            unique_together={('rank', 'ability', 'question')},
        ),
    ]
