# Generated by Django 2.1.7 on 2019-04-08 14:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0031_auto_20190408_1553'),
        ('scoring_360', '0006_auto_20190408_1606'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scoring360SeamanAbility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Метка времени')),
                ('ability_value', models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Оценка')),
                ('ability', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scoring_360.Ability360', verbose_name='Компетенция')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise_from', to='crewing.Seamans', verbose_name='Кто оценивал')),
                ('seaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appraise_to', to='crewing.Seamans', verbose_name='Оцениваемый моряк')),
            ],
            options={
                'verbose_name': 'Оценка 360',
                'verbose_name_plural': 'Оценки 360',
                'ordering': ['seaman', 'date'],
            },
        ),
    ]
