# Generated by Django 2.1.7 on 2019-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seamans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(db_index=True, max_length=128, verbose_name='Фамилия')),
                ('first_name', models.CharField(db_index=True, max_length=128, verbose_name='Имя')),
            ],
            options={
                'verbose_name': 'Моряк',
                'verbose_name_plural': 'Моряки',
            },
        ),
    ]
