# Generated by Django 2.1.7 on 2019-03-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0002_auto_20190320_1634'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamans',
            name='first_name_en',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Имя (EN)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='first_name_ru',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Имя (RU)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='first_name_ua',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Имя (UA)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='last_name_en',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Фамилия (EN)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='last_name_ru',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Фамилия (RU)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='last_name_ua',
            field=models.CharField(db_index=True, max_length=128, verbose_name='Фамилия (UA)'),
        ),
    ]
