# Generated by Django 2.1.7 on 2019-03-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0006_seaman360ability_seaman360question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaman360question',
            name='rank',
        ),
        migrations.AddField(
            model_name='seaman360question',
            name='rank',
            field=models.ManyToManyField(to='crewing.Ranks', verbose_name='Должность'),
        ),
    ]
