# Generated by Django 2.1.7 on 2019-03-22 07:47

import crewing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0007_auto_20190321_1619'),
    ]

    operations = [
        migrations.AddField(
            model_name='seamans',
            name='foto',
            field=models.ImageField(default=' ', upload_to=crewing.models.get_timestamp_path, verbose_name='Фото'),
            preserve_default=False,
        ),
    ]
