# Generated by Django 2.1.7 on 2019-03-22 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0009_auto_20190322_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaman360question',
            name='ability',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Организаторские способности'), (2, 'Дисциплинированность'), (3, 'Старательность'), (4, 'Работа в команде'), (5, 'Работоспособность'), (6, 'Ответственность'), (7, 'Стрессоустойчивость'), (8, 'Лидерство'), (9, 'Уверенность в себе'), (10, 'Трудолюбие')], db_index=True, verbose_name='Компетенция'),
        ),
    ]
