# Generated by Django 2.1.7 on 2019-03-22 10:41

import crewing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0011_auto_20190322_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamans',
            name='foto',
            field=models.ImageField(default='seaman.png', null=True, upload_to=crewing.models.get_timestamp_path, verbose_name='Фото'),
        ),
    ]
