# Generated by Django 2.1.7 on 2019-03-22 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0012_auto_20190322_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seaman360Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True, verbose_name='Метка времени')),
                ('ability1', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Организаторские способности')),
                ('ability2', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Дисциплинированность')),
                ('ability3', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Старательность')),
                ('ability4', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Работа в команде')),
                ('ability5', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Работоспособность')),
                ('ability6', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Ответственность')),
                ('ability7', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Стрессоустойчивость')),
                ('ability8', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Лидерство')),
                ('ability9', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Уверенность в себе')),
                ('ability10', models.DecimalField(db_index=True, decimal_places=1, max_digits=2, verbose_name='Трудолюбие')),
                ('appraiser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_from', to='crewing.Seamans', verbose_name='Кто оценивал')),
                ('seaman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rates_to', to='crewing.Seamans', verbose_name='Оцениваемый моряк')),
            ],
            options={
                'verbose_name': 'Рейтинг 360 (моряки)',
                'verbose_name_plural': 'Рейтинги 360 (моряки)',
            },
        ),
    ]
