# Generated by Django 2.1.7 on 2019-03-22 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0013_seaman360rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seamans',
            name='first_name_ua',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Имя (UA)'),
        ),
        migrations.AlterField(
            model_name='seamans',
            name='last_name_ua',
            field=models.CharField(blank=True, db_index=True, max_length=128, null=True, verbose_name='Фамилия (UA)'),
        ),
    ]
