# Generated by Django 2.1.7 on 2019-03-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0014_auto_20190322_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='seamans',
            name='last_rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crewing.Ranks', verbose_name='Последняя должность'),
        ),
    ]
