# Generated by Django 2.1.7 on 2019-03-25 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0015_seamans_last_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contracts',
            name='sign_off_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата списания'),
        ),
    ]
