# Generated by Django 2.1.7 on 2019-03-26 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0016_auto_20190325_1527'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contracts',
            options={'ordering': ['-sign_in_date'], 'verbose_name': 'Контракт', 'verbose_name_plural': 'Контракты'},
        ),
        migrations.AlterField(
            model_name='seaman360question',
            name='ability',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crewing.Seaman360Ability', verbose_name='Компетенция'),
        ),
    ]
