# Generated by Django 2.1.7 on 2019-03-26 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0017_auto_20190326_1255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seaman360question',
            options={'ordering': ['ability', 'question'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='seaman360question',
            name='rank',
            field=models.ManyToManyField(related_name='Компетенции', to='crewing.Ranks', verbose_name='Должность'),
        ),
    ]
