# Generated by Django 2.1.7 on 2019-03-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0018_auto_20190326_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='abilities',
            field=models.ManyToManyField(related_name='Должности', to='crewing.Seaman360Ability'),
        ),
    ]
