# Generated by Django 2.1.7 on 2019-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0019_ranks_abilities'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranks',
            name='abilities',
        ),
        migrations.AddField(
            model_name='seaman360ability',
            name='ranks',
            field=models.ManyToManyField(to='crewing.Ranks'),
        ),
    ]
