# Generated by Django 2.1.7 on 2019-03-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0020_auto_20190326_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaman360ability',
            name='ranks',
            field=models.ManyToManyField(related_name='abilities', to='crewing.Ranks'),
        ),
    ]
