# Generated by Django 2.1.7 on 2019-03-27 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0022_auto_20190327_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability1',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Организаторские способности'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability10',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Трудолюбие'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability2',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Дисциплинированность'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability3',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Старательность'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability4',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Работа в команде'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability5',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Работоспособность'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability6',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Ответственность'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability7',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Стрессоустойчивость'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability8',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Лидерство'),
        ),
        migrations.AlterField(
            model_name='seaman360rating',
            name='ability9',
            field=models.DecimalField(blank=True, db_index=True, decimal_places=1, default=None, max_digits=2, null=True, verbose_name='Уверенность в себе'),
        ),
    ]
