# Generated by Django 2.1.7 on 2019-04-01 11:23

import crewing.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0024_auto_20190401_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinions',
            name='opinion_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to=crewing.models.get_opinionfile_path, verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='opinions',
            name='contract',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='crewing.Contracts', verbose_name='Контракт'),
        ),
    ]
