# Generated by Django 2.1.7 on 2019-04-05 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0025_auto_20190401_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinions',
            name='contract',
        ),
        migrations.RemoveField(
            model_name='opinions',
            name='seaman',
        ),
        migrations.DeleteModel(
            name='Opinions',
        ),
    ]
