# Generated by Django 2.1.7 on 2019-04-07 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0026_auto_20190405_2233'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seaman360ability',
            name='ranks',
        ),
        migrations.RemoveField(
            model_name='seaman360question',
            name='ability',
        ),
        migrations.RemoveField(
            model_name='seaman360question',
            name='rank',
        ),
        migrations.RemoveField(
            model_name='seaman360rating',
            name='appraiser',
        ),
        migrations.RemoveField(
            model_name='seaman360rating',
            name='seaman',
        ),
        migrations.DeleteModel(
            name='Seaman360Ability',
        ),
        migrations.DeleteModel(
            name='Seaman360Question',
        ),
        migrations.DeleteModel(
            name='Seaman360Rating',
        ),
    ]
