# Generated by Django 2.1.7 on 2019-04-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scoring_360', '0004_auto_20190408_1319'),
        ('crewing', '0028_auto_20190408_1246'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='abilities',
            field=models.ManyToManyField(related_name='ranks', to='scoring_360.Ability360', verbose_name='Компетенции'),
        ),
    ]
