# Generated by Django 2.1.7 on 2019-04-08 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0030_ranks_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ranks',
            name='abilities',
        ),
        migrations.RemoveField(
            model_name='ranks',
            name='questions',
        ),
    ]
