# Generated by Django 2.1.7 on 2019-04-10 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0031_auto_20190408_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name_ru', models.CharField(db_index=True, max_length=128, verbose_name='Фамилия (RU)')),
                ('first_name_ru', models.CharField(db_index=True, max_length=128, verbose_name='Имя (RU)')),
            ],
            options={
                'verbose_name': 'Сотрудник',
                'verbose_name_plural': 'Сотрудники',
            },
        ),
        migrations.RemoveField(
            model_name='seamans',
            name='first_name_ru',
        ),
        migrations.RemoveField(
            model_name='seamans',
            name='id',
        ),
        migrations.RemoveField(
            model_name='seamans',
            name='last_name_ru',
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('person_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crewing.Person')),
            ],
            options={
                'verbose_name': 'Офисный работник',
                'verbose_name_plural': 'Офисные работники',
            },
            bases=('crewing.person', models.Model),
        ),
        migrations.AddField(
            model_name='seamans',
            name='person_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crewing.Person'),
            preserve_default=False,
        ),
    ]
