# Generated by Django 2.1.7 on 2019-04-10 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0032_auto_20190410_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='ranks',
            name='is_officer',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Офисная должность'),
        ),
    ]
