# Generated by Django 2.1.7 on 2019-04-10 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0033_ranks_is_officer'),
    ]

    operations = [
        migrations.AddField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='crewing.Ranks', verbose_name='Должность'),
        ),
    ]
