# Generated by Django 2.1.7 on 2019-04-10 10:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crewing', '0034_officer_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='officer',
            name='rank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crewing.Ranks', verbose_name='Должность'),
        ),
    ]
